"""Streamlit app for the hybrid recommender capstone.

Run from the repo root:
    streamlit run app/app.py

The data is the synthetic Amazon-Electronics-style dataset from
src/pipeline.py (seed 42), so nothing needs to be downloaded. The first load
trains all models (about 15-20 seconds); later loads use the cache.

The deployed app asks for a password, which is read from the Streamlit
secrets (`password = "..."`). If no password is set, for example when running
locally without .streamlit/secrets.toml, the app opens without one.
"""

import hmac
import os
import sys

import pandas as pd
import streamlit as st

sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))
from recommender import (  # noqa: E402
    FINAL_ALPHA,
    FINAL_LAMBDA,
    MODEL_NAMES,
    build_models,
    evaluate_models,
    held_out_liked,
    ndcg_by_tier,
    recommend,
    user_history,
)

st.set_page_config(page_title="Hybrid Recommender", page_icon="🛒", layout="wide")


def get_password():
    """Password from the Streamlit secrets, or None if it is not set."""
    try:
        return st.secrets["password"]
    except Exception:
        return None


def check_password():
    """Show a password box until the correct password is entered."""
    password = get_password()
    if password is None or st.session_state.get("logged_in"):
        return True

    st.title("Hybrid Product Recommender")
    entered = st.text_input("Password", type="password")
    if entered:
        if hmac.compare_digest(entered, password):
            st.session_state["logged_in"] = True
            st.rerun()
        st.error("Incorrect password.")
    return False


# checked before the models are loaded, so nothing runs without the password
if not check_password():
    st.stop()


@st.cache_resource(show_spinner="Training models (first load only)...")
def load():
    return build_models(seed=42)


@st.cache_data(show_spinner="Scoring models on the test set...")
def load_metrics():
    state, _, scores, _ = load()
    return evaluate_models(state, scores), ndcg_by_tier(state, scores)


state, products, scores, pop = load()
n_hist = pd.Series(state["n_hist"], index=state["user_ids"])

# only customers with liked items in the test period are listed, since
# otherwise the recommendations cannot be checked against held-out data
test_liked_users = sorted(state["test"][state["test"].rating >= 4].user_id.unique())

# ---------------- sidebar ----------------
st.sidebar.header("Settings")
model_name = st.sidebar.selectbox("Model", MODEL_NAMES, index=0)
k = st.sidebar.slider("Number of recommendations (K)", 5, 20, 10)

tier = st.sidebar.radio(
    "Customer history (training interactions)",
    ["Any", "1-2", "3-4", "5-9", "10-19", "20+"],
    help="Low-history customers are the cold-start case.",
)
tier_ranges = {"1-2": (1, 2), "3-4": (3, 4), "5-9": (5, 9), "10-19": (10, 19), "20+": (20, 10**6)}
if tier == "Any":
    options = test_liked_users
else:
    lo, hi = tier_ranges[tier]
    options = [u for u in test_liked_users if lo <= n_hist[u] <= hi]

if not options:
    st.sidebar.warning("No customers in this group.")
    st.stop()

user_id = st.sidebar.selectbox(f"Customer ({len(options)} available)", options)
st.sidebar.caption(
    "Synthetic data only, no real customers. IDs are generated by the data script."
)

# ---------------- main ----------------
st.title("Hybrid Product Recommender")
st.write(
    "SVD collaborative filtering blended with TF-IDF content similarity, "
    "for a sparse electronics catalog. DSC-590 capstone project."
)

tab_rec, tab_perf, tab_about = st.tabs(["Recommendations", "Model performance", "About"])

with tab_rec:
    hist = user_history(state, products, user_id)
    liked_test = held_out_liked(state, user_id, "test")
    fav_cat = hist.category.value_counts().index[0] if len(hist) else "-"

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Training interactions", int(n_hist[user_id]))
    c2.metric("Most rated category", fav_cat)
    c3.metric("Liked items in test period", len(liked_test))

    rec_ids, rec_scores = recommend(scores[model_name], state, user_id, k=k)
    hits = sum(p in liked_test for p in rec_ids)
    c4.metric(f"Hits in top {k}", hits)

    left, right = st.columns([1, 1.4])

    with left:
        st.subheader("Rating history (training period)")
        st.dataframe(
            hist[["product_id", "category", "price_bucket", "rating"]],
            hide_index=True,
            width="stretch",
        )

    with right:
        st.subheader(f"Top {k} from: {model_name}")
        pop_rank = pd.Series(pop, index=state["prod_ids"]).rank(ascending=False).astype(int)
        recs = pd.DataFrame({"product_id": rec_ids, "score": rec_scores}).merge(
            products, on="product_id", how="left"
        )
        recs.insert(0, "rank", range(1, len(recs) + 1))
        recs["popularity rank"] = recs.product_id.map(pop_rank)
        recs["liked in test?"] = recs.product_id.isin(liked_test).map({True: "yes", False: ""})
        st.dataframe(
            recs[["rank", "product_id", "category", "price_bucket", "score",
                  "popularity rank", "liked in test?"]],
            hide_index=True,
            width="stretch",
            column_config={"score": st.column_config.NumberColumn(format="%.3f")},
        )
        st.caption(
            "\"liked in test?\" = the customer rated this product 4+ stars in the "
            "held-out test period. Popularity rank 1 = most rated product in training."
        )

    if n_hist[user_id] <= 3:
        st.info(
            "This is a low-history customer. The original adaptive hybrid gave "
            "customers like this zero SVD weight and the results were close to random. "
            "The final model keeps the SVD signal for everyone."
        )

with tab_perf:
    overall, tiers = load_metrics()
    st.subheader("Held-out test set (K = 10)")
    st.dataframe(
        overall.style.format("{:.4f}").format("{:.0%}", subset=["catalog coverage"]),
        width="stretch",
    )
    st.write(
        "The final hybrid has the best NDCG@10. The fixed 50/50 blend covers more of "
        "the catalog, so there is still a trade-off between accuracy and coverage."
    )

    st.subheader("NDCG@10 by customer history")
    st.bar_chart(tiers, stack=False, height=360)
    st.caption("Tiers are the number of training interactions per customer.")

with tab_about:
    st.markdown(
        f"""
**Final model**

- SVD on the user-item rating matrix, 12 latent factors
- TF-IDF on product category, cosine similarity to the products a customer rated 4+
- Blend: {FINAL_ALPHA} x SVD + {1 - FINAL_ALPHA:.1f} x content
- Small popularity penalty before ranking (lambda = {FINAL_LAMBDA}) to show more of the catalog

All settings were picked on the validation set, the test set was only used for the
final numbers. Details are in `notebooks/advanced_analysis_refinement_final.ipynb`.

**Limitations**

- The data is synthetic. Category is the only real preference signal in it, so the
  "drop price" result may not hold on real data.
- New products are not tested. The test set only has products that appear in training.
- Offline ratings are not the same as clicks or purchases.
"""
    )
