"""Streamlit app for the hybrid recommender capstone.

Run from the repo root:
    streamlit run app/app.py

The data is the synthetic Amazon-Electronics-style dataset from
src/pipeline.py (seed 42), so nothing needs to be downloaded. The first load
trains all models (about 15-20 seconds); later loads use the cache.

The deployed app asks for a password, which is read from the Streamlit
secrets (`password = "..."`). If no password is set, for example when running
locally without .streamlit/secrets.toml, the app opens without one.
"""

import hmac
import os
import sys

import altair as alt
import pandas as pd
import streamlit as st

sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))
from recommender import (  # noqa: E402
    FINAL_ALPHA,
    FINAL_LAMBDA,
    MODEL_NAMES,
    SVD_FACTORS,
    build_models,
    evaluate_models,
    explain,
    held_out_liked,
    ndcg_by_tier,
    recommend,
    user_history,
)

st.set_page_config(page_title="Hybrid Recommender", page_icon="🛒", layout="wide")

# chart colours (blue, orange, aqua, yellow), checked for colour-blind
# separation and contrast on both light and dark backgrounds
MODEL_COLORS = ["#3987e5", "#d95926", "#199e70", "#c98500"]


def get_password():
    """Password from the Streamlit secrets, or None if it is not set."""
    try:
        return st.secrets["password"]
    except Exception:
        return None


def check_password():
    """Show a password box until the correct password is entered."""
    password = get_password()
    if password is None or st.session_state.get("logged_in"):
        return True

    st.title("Hybrid Product Recommender")
    entered = st.text_input("Password", type="password")
    if entered:
        if hmac.compare_digest(entered, password):
            st.session_state["logged_in"] = True
            st.rerun()
        st.error("Incorrect password.")
    return False


# checked before the models are loaded, so nothing runs without the password
if not check_password():
    st.stop()


@st.cache_resource(show_spinner="Training models (first load only)...")
def load():
    return build_models(seed=42)


@st.cache_data(show_spinner="Scoring models on the test set...")
def load_metrics():
    state, _, scores, _ = load()
    return evaluate_models(state, scores), ndcg_by_tier(state, scores)


state, products, scores, pop = load()
n_hist = pd.Series(state["n_hist"], index=state["user_ids"])

# only customers with liked items in the test period are listed, since
# otherwise the recommendations cannot be checked against held-out data
test_liked_users = sorted(state["test"][state["test"].rating >= 4].user_id.unique())

# ---------------- sidebar ----------------
st.sidebar.header("Settings")
model_name = st.sidebar.selectbox("Model", MODEL_NAMES, index=0)
k = st.sidebar.slider("Number of recommendations (K)", 5, 20, 10)

tier = st.sidebar.radio(
    "Customer history (training interactions)",
    ["Any", "1-2", "3-4", "5-9", "10-19", "20+"],
    help="Low-history customers are the cold-start case.",
)
tier_ranges = {"1-2": (1, 2), "3-4": (3, 4), "5-9": (5, 9), "10-19": (10, 19), "20+": (20, 10**6)}
if tier == "Any":
    options = test_liked_users
else:
    lo, hi = tier_ranges[tier]
    options = [u for u in test_liked_users if lo <= n_hist[u] <= hi]

if not options:
    st.sidebar.warning("No customers in this group.")
    st.stop()

def first_with_hit(customers):
    """Index of the first customer with at least one hit from the final model,
    so the app opens on an example where the recommendations can be checked."""
    for i, u in enumerate(customers):
        rec_ids, _ = recommend(scores["Final hybrid"], state, u, k=10)
        if held_out_liked(state, u, "test") & set(rec_ids):
            return i
    return 0


user_id = st.sidebar.selectbox(
    f"Customer ({len(options)} available)", options, index=first_with_hit(options)
)
st.sidebar.caption(
    "Synthetic data only, no real customers. IDs are generated by the data script."
)

# ---------------- main ----------------
st.title("Hybrid Product Recommender")
st.write(
    "Personalised product recommendations for an electronics catalog, combining "
    "collaborative filtering (SVD) with content-based filtering (TF-IDF) to support "
    "customers with little rating history. All data is synthetic."
)
st.caption(
    "Use the sidebar to choose a model and a customer profile. The About tab describes "
    "the methodology, evaluation design and key findings."
)

tab_rec, tab_perf, tab_about, tab_help = st.tabs(
    ["Recommendations", "Model performance", "About", "Help & contact"]
)

with tab_rec:
    hist = user_history(state, products, user_id)
    liked_test = held_out_liked(state, user_id, "test")
    fav_cat = hist.category.value_counts().index[0] if len(hist) else "-"

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Training interactions", int(n_hist[user_id]))
    c2.metric("Most rated category", fav_cat)
    c3.metric("Liked items in test period", len(liked_test))

    rec_ids, rec_scores = recommend(scores[model_name], state, user_id, k=k)
    hits = sum(p in liked_test for p in rec_ids)
    c4.metric(f"Hits in top {k}", hits)

    st.subheader(f"Top {k} recommendations: {model_name}")
    pop_rank = pd.Series(pop, index=state["prod_ids"]).rank(ascending=False).astype(int)
    recs = pd.DataFrame({"product_id": rec_ids, "score": rec_scores}).merge(
        products, on="product_id", how="left"
    )
    recs.insert(0, "rank", range(1, len(recs) + 1))
    recs["popularity rank"] = recs.product_id.map(pop_rank)
    recs["liked in test?"] = recs.product_id.isin(liked_test).map({True: "yes", False: ""})
    recs["why recommended"] = explain(model_name, state, products, user_id, rec_ids, pop_rank)
    st.dataframe(
        recs[["rank", "product_id", "category", "price_bucket", "score",
              "popularity rank", "liked in test?", "why recommended"]],
        hide_index=True,
        width="stretch",
        column_config={
            "rank": st.column_config.NumberColumn(width="small"),
            "product_id": st.column_config.TextColumn("product", width="small"),
            "category": st.column_config.TextColumn(width="small"),
            "price_bucket": st.column_config.TextColumn("price", width="small"),
            "score": st.column_config.NumberColumn(format="%.3f", width="small"),
            "liked in test?": st.column_config.TextColumn(width="small"),
            "why recommended": st.column_config.TextColumn(width="large"),
        },
    )
    st.caption(
        "\"liked in test?\" = the customer rated this product 4+ stars in the held-out "
        "test period. Popularity rank 1 = most rated product in training. \"why "
        "recommended\" summarises the signal that placed the product in the list; in "
        "the final hybrid, products from the same category are then ordered by the "
        "ratings of customers with similar tastes (SVD)."
    )

    st.subheader("Rating history (training period)")
    st.dataframe(
        hist[["product_id", "category", "price_bucket", "rating"]],
        hide_index=True,
        width="stretch",
        column_config={
            "product_id": st.column_config.TextColumn("product"),
            "price_bucket": st.column_config.TextColumn("price"),
        },
    )

    if n_hist[user_id] <= 3:
        st.info(
            "This is a low-history customer. The original adaptive hybrid gave "
            "customers like this zero SVD weight and the results were close to random. "
            "The final model keeps the SVD signal for everyone."
        )

with tab_perf:
    overall, tiers = load_metrics()
    st.subheader("Held-out test set (K = 10)")

    def highlight_selected(row):
        style = "background-color: rgba(57, 135, 229, 0.18); font-weight: 600"
        return [style if row.name == model_name else "" for _ in row]

    st.dataframe(
        overall.style.apply(highlight_selected, axis=1)
        .format("{:.4f}")
        .format("{:.0%}", subset=["catalog coverage"]),
        width="stretch",
    )
    st.caption(f"The highlighted row is the model selected in the sidebar ({model_name}).")

    # one fixed colour per model, the same in every chart
    model_colors = alt.Scale(domain=MODEL_NAMES, range=MODEL_COLORS)
    is_selected = alt.datum.model == model_name

    left, right = st.columns(2)
    with left:
        st.markdown("**Ranking accuracy by model**")
        acc = (
            overall[["precision@10", "recall@10", "NDCG@10"]]
            .reset_index()
            .melt("model", var_name="metric", value_name="value")
        )
        acc_chart = (
            alt.Chart(acc)
            .mark_bar(cornerRadiusTopLeft=4, cornerRadiusTopRight=4)
            .encode(
                x=alt.X("metric:N", title=None, sort=["precision@10", "recall@10", "NDCG@10"],
                        axis=alt.Axis(labelAngle=0)),
                xOffset=alt.XOffset("model:N", sort=MODEL_NAMES),
                y=alt.Y("value:Q", title="Score"),
                color=alt.Color("model:N", scale=model_colors,
                                legend=alt.Legend(title=None, orient="bottom")),
                opacity=alt.condition(is_selected, alt.value(1.0), alt.value(0.45)),
                tooltip=["model", "metric", alt.Tooltip("value:Q", format=".4f")],
            )
            .properties(height=320)
        )
        st.altair_chart(acc_chart, use_container_width=True)
        st.caption("Higher is better. The selected model is shown at full colour.")

    with right:
        st.markdown("**Accuracy vs catalog coverage**")
        trade = overall.reset_index().rename(
            columns={"NDCG@10": "ndcg", "catalog coverage": "coverage"}
        )
        base = alt.Chart(trade).encode(
            x=alt.X("coverage:Q", title="Catalog coverage",
                    axis=alt.Axis(format="%"), scale=alt.Scale(domain=[0, 0.8])),
            y=alt.Y("ndcg:Q", title="NDCG@10", scale=alt.Scale(domain=[0.06, 0.13])),
        )
        points = base.mark_circle(opacity=1, stroke="white", strokeWidth=2).encode(
            color=alt.Color("model:N", scale=model_colors, legend=None),
            size=alt.condition(is_selected, alt.value(380), alt.value(160)),
            tooltip=["model", alt.Tooltip("ndcg:Q", title="NDCG@10", format=".4f"),
                     alt.Tooltip("coverage:Q", title="coverage", format=".0%")],
        )
        labels = base.mark_text(align="left", dx=12, fontSize=12).encode(text="model:N")
        st.altair_chart((points + labels).properties(height=320), use_container_width=True)
        st.caption(
            "Top-right is best. The final hybrid is the most accurate, while the fixed "
            "50/50 blend recommends a wider share of the catalog."
        )

    st.subheader("NDCG@10 by customer history")
    tier_df = (
        tiers.rename_axis("tier").reset_index()
        .melt("tier", var_name="model", value_name="ndcg")
    )
    tier_chart = (
        alt.Chart(tier_df)
        .mark_bar(cornerRadiusTopLeft=4, cornerRadiusTopRight=4)
        .encode(
            x=alt.X("tier:N", title="Training interactions per customer",
                    sort=list(tiers.index), axis=alt.Axis(labelAngle=0)),
            xOffset=alt.XOffset("model:N", sort=MODEL_NAMES),
            y=alt.Y("ndcg:Q", title="NDCG@10"),
            color=alt.Color("model:N", scale=model_colors,
                            legend=alt.Legend(title=None, orient="bottom")),
            opacity=alt.condition(is_selected, alt.value(1.0), alt.value(0.45)),
            tooltip=["tier", "model", alt.Tooltip("ndcg:Q", title="NDCG@10", format=".4f")],
        )
        .properties(height=340)
    )
    st.altair_chart(tier_chart, use_container_width=True)
    st.caption(
        "Customers with 1-2 or 3-4 training interactions are the cold-start case. "
        "The final hybrid has the highest NDCG@10 in every tier, including these."
    )

with tab_about:
    events_f = state["events_f"]
    st.markdown(
        f"""
### About this project

This project examines whether combining collaborative filtering and content-based
filtering produces better top-10 recommendations than either method alone on sparse
e-commerce data. Particular attention is given to customers with little rating history,
for whom collaborative filtering alone has limited information to work with (the
*cold-start problem*).

### How to use this app

1. **Choose a model** in the sidebar. The final hybrid is selected by default; the other
   models are included for comparison.
2. **Filter customers by history** to focus on low-history customers (1-2 or 3-4
   ratings), the cold-start case, or on more established customers.
3. **Select a customer.** The *Recommendations* tab shows their past ratings next to the
   model's top-K products. Products the customer rated 4 or 5 stars in the held-out test
   period are marked as hits.
4. **Model performance** compares all models on the held-out test set, overall and by
   customer history.

### Data

The data is fully synthetic and was generated to resemble the Amazon Electronics review
data: very sparse, mostly positive ratings, and a long tail of rarely rated products.
After filtering there are {len(events_f):,} ratings from {events_f.user_id.nunique():,}
customers across {events_f.product_id.nunique():,} products. No real customer information
is used.

### Models compared

| Model | Description |
| --- | --- |
| **Final hybrid** | {FINAL_ALPHA} × SVD + {1 - FINAL_ALPHA:.1f} × content similarity (category), with a small popularity penalty (λ = {FINAL_LAMBDA}) |
| SVD only | Collaborative filtering with {SVD_FACTORS} latent factors |
| Fixed 50/50 hybrid | The starting design: equal blend of SVD and content (category and price) |
| Most popular | Non-personalised baseline: the most-rated products in training |

### How the models were evaluated

- **Time-based split:** the earliest 70% of ratings are used for training, the next 10%
  for validation and the last 20% for testing, so models are always evaluated on later
  behaviour.
- **Tuning on validation only:** every setting (blend weight, content features,
  popularity penalty) was selected on the validation set. The test set was used once,
  for the final results.
- **Metrics:** Precision@10, Recall@10 and NDCG@10, which rewards relevant items placed
  near the top of the list. A product counts as relevant if the customer rated it 4 or 5
  stars in the test period. **Catalog coverage**, the share of products recommended to
  at least one customer, measures how much of the catalog the model exposes.

### Key findings

- The final hybrid achieved the highest NDCG@10 (0.119), compared with 0.100 for SVD
  alone. The difference is statistically significant (paired Wilcoxon test) and held
  across five generated datasets.
- The original adaptive design, which gave low-history customers no collaborative
  filtering weight, performed close to random for customers with 1-2 ratings. Keeping a
  share of collaborative filtering for every customer resolved this.
- Removing price from the content features gave the largest single improvement.
- There is a trade-off between accuracy and coverage: the fixed 50/50 blend recommends a
  wider range of products (54% vs 46% of the catalog).

### Limitations

- The data is synthetic, with product category as its main preference signal, so the
  results may not transfer directly to real customers.
- Products that are new in the test period were not evaluated, so cold start is only
  examined for customers.
- Ratings are an offline proxy. A high rating is not the same as a click or a purchase,
  and online testing would be needed to measure real impact.

### Privacy

No personal data is used. The pipeline still includes safeguards suitable for real data:
a minimum set of data fields, pseudonymised customer IDs, file integrity checks and
encrypted exports.

**Source code:** [github.com/hgarg/recommender-project](https://github.com/hgarg/recommender-project)
"""
    )

with tab_help:
    st.subheader("Glossary")
    st.markdown(
        """
| Term | Meaning |
| --- | --- |
| **Cold start** | Recommending for customers with very little rating history, where collaborative filtering has little to learn from. |
| **Collaborative filtering (SVD)** | Learns from the rating patterns of all customers; products liked by customers with similar tastes are recommended. |
| **Content-based filtering (TF-IDF)** | Recommends products whose attributes (here, category) match products the customer rated highly. |
| **Hit** | A recommended product that the customer rated 4 or 5 stars in the held-out test period. |
| **Precision@10** | The share of the 10 recommended products that are hits. |
| **Recall@10** | The share of the customer's liked test-period products that appear in the top 10. |
| **NDCG@10** | A ranking score between 0 and 1 that gives more credit to hits placed near the top of the list. |
| **Catalog coverage** | The share of all products recommended to at least one customer; higher means a wider range of products is shown. |
| **Popularity rank** | The product's position by number of ratings in the training period (1 = most rated). |
"""
    )

    st.subheader("Frequently asked questions")
    with st.expander("Why does a customer have 0 hits?"):
        st.write(
            "Most customers like only one or two products in the test period, out of "
            "almost 2,000 available, so many top-10 lists contain no hit even when the "
            "recommendations are reasonable. This is why results are averaged over all "
            "customers on the Model performance tab rather than judged on one customer."
        )
    with st.expander("Why are some recommendation scores identical?"):
        st.write(
            "The content-based part compares products by category, so products in the "
            "same category receive the same content score. In the final hybrid, the "
            "collaborative part and a small popularity penalty then decide the order "
            "within each category."
        )
    with st.expander("Why are only some customers listed?"):
        st.write(
            "Only customers who rated at least one product 4 or 5 stars in the test "
            "period are listed. For other customers there is nothing to compare the "
            "recommendations against."
        )
    with st.expander("Why is the data synthetic?"):
        st.write(
            "Synthetic data avoids any use of personal information and makes the whole "
            "study reproducible from a fixed random seed. It was generated to resemble "
            "the Amazon Electronics review data, but results on real customers may differ."
        )
    with st.expander("How is \"why recommended\" decided?"):
        st.write(
            "The explanation follows how each model scores products. For the final "
            "hybrid, it states how many of the customer's 4-5 star products share the "
            "recommended product's category; when there is no such product, the "
            "recommendation comes from the ratings of customers with similar tastes."
        )

    st.subheader("Contact")
    with st.container(border=True):
        st.markdown(
            """
#### Student
Hybrid Product Recommender project

📧 &nbsp;[student@example.com](mailto:student@example.com)

🔗 &nbsp;[github.com/hgarg/recommender-project](https://github.com/hgarg/recommender-project)

For questions about the methodology, the results or access to the application, please
get in touch by email.
"""
        )
